### ISSUE TITLE
Prod: Improve View Excused History page response time

### ISSUE THREAD

**Issue by steffipravasi** [bcgov/performance#1051]
The page on test is throwing an Ajax error after taking long while loading.
The page on Prod is taking 10s which is not good and shouldn't take long to load 3500 entries.

**Comment by jizhaogit** [comment]
test ajax error is fixed. but loading time is still a little bit long. will check with Dennis to see what we can do for this problem.

**Comment by jessicahjwu** [comment]
Pipelines: Product Backlog
No sprint assigned
Estimate: 3
Epics: Excusing Employees, DevOps

**Comment by telusdcinco** [comment]
MIGRATION NOTES:

Run 'php artisan migrate'

**Comment by telusdcinco** [comment]
@jizhaogit Please review the code changes.

**Comment by steffipravasi** [comment]
@telusdcinco 
I am still receiving the Ajax error on the view excused history page
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGlsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30748ef50fa53d412575c2a20175f7c310532c12/Screenshot%202024-03-01%20at%201.34.40%E2%80%AFPM.png" alt="Screenshot 2024-03-01 at 1.34.40 PM.png" />

**Comment by steffipravasi** [comment]
As discussed with Dennis, the response time for the View Excused History page is better than before. The page still gives an Ajax error when there's some background process running. We'll need to confirm the response on prod once deployed.
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHlzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94d5d894500cf712859e73622d4f41030b20fce1/Screenshot%202024-03-04%20at%202.47.13%E2%80%AFPM.png" alt="Screenshot 2024-03-04 at 2.47.13 PM.png" />

**Comment by jessicahjwu** [comment]
Response time for the view excuse history page still takes longer than usual, however the list is showing up properly. Will continue to monitor.
