### ISSUE TITLE
As a Sys / HR Admin I want to see basic reporting information within the app

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#436]
The MVP reporting functionality for pilot launch will include:

- [x] Goal summary
- [x] Conversations summary
- [x] Shared employee summary
- [x] Excused employee summary

I've attached an Excel spreadsheet with a tab for each. The general concept is a high level graphic that summarizes the particular data set for the group of employees that the Sys / HR Admin has access to with the ability to export the underlying data if they want to see individual rows in Excel. I don't think this actually requires much more than we're already doing for the My Team view of the employees. We just need to roll it up into a graphic.

See attached.

[https://app.zenhub.com/files/329107952/9734be37-3c20-4c20-b017-e14ff9c97228/download](https://app.zenhub.com/files/329107952/9734be37-3c20-4c20-b017-e14ff9c97228/download)

**Comment by phoebesolomon** [comment]
Goals Summary:

![HR Admin - Statistics and Reports _ Goal Summary.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/c4bf67dd-7138-43cf-be95-478f6fcff186)

Conversations Summary:

![HR Admin - Statistics and Reports _ Conversations Summary.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/52208d29-0095-43d1-b384-7c8f463769e5)

Shared Employees Summary:

![HR Admin - Statistics and Reports _ Shared Summary.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/d0dd6016-1774-4661-9097-b3da9e7a16ab)

Excused Employees Summary:

![HR Admin - Statistics and Reports _ Excused Summary.jpg](https://images.zenhubusercontent.com/60621c7c61819dc090d375b2/41a8caa8-19d8-45c0-a52a-afc4c0df325b)

**Comment by Travis-A-Clark** [comment]
@phoebesolomon This looks great! Thanks for the quick turnaround. I'll re-assign to KK for his dev estimate.

**Comment by jp-Telus** [comment]
Per the attached spreadsheet, the fisrt 2 tabs were developed and also deployed on DEV region for review.

In DEV region, I granted 'hr admin' role to"executive1@example.com", and so that he can review the goals and conversation statistcis charts.

command run in tinker:
User::find(10)->assignRole('hr admin');

Thanks.

**Comment by jp-Telus** [comment]
Work done
1. Another 2 tabs were added for Shared Employees and Excused Employees Summary
2. change the "Goal" and "Conversation" export columns per requirement 
3. fix typo on the exporte file name 
4. Rewrite the logic for the conversation due per requirements.

Code changes pushed to Repo. and will be deployed on next schedule depolyment.

Thank you.

**Comment by Travis-A-Clark** [comment]
@jp-Telus Thanks for this! Is there any way we can change the column headers Program, Division, Branch to Level 1, Level 2, Level 3?

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/c08442f8-66c3-484e-9d1a-6484a972e551)

**Comment by jp-Telus** [comment]
Development completed and ready for deployment 

Migration Step after the deployment:
1. php asrtian migrate
2. clear up the sync user profile job history - by SQL : delete from job_sched_audit jsa where job_name = 'command:SyncUserProfiles';
3. php asrtian command:syncUserProfile

Work done.
1. Due to performance issue, the new set of the Statistics and Reporting pages were developed for System administrator
2. The title on the excel report were fixed
3. New business logic added in HR Admin reporting, only the employee were defined in the admin_orgs table.
4. Fixed some minor business logic issues in conversation summary.

Thank you.

**Comment by Travis-A-Clark** [comment]
@jp-Telus Could we add an organization filter to the top of each reporting page (see below for example) for both HR Admin and Sys Admin?

Could we also add a bar chart to the Goals Summary page below the four pie charts called "Active Goal Tags" that is a count of how many times each type of goal tag has been used? It would include No Tag, as well as one column for each of the goal tags available.
<br>
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/5867b8e2-7b2a-4a16-a082-e031019157e5)
<br>
Something simple like this where each column is one of the goal tags:
![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/10eb12e7-3cbb-46c8-a701-93e08227deb2)

**Comment by jp-Telus** [comment]
Per new requirements, here is the work done and deployed on DEV
1. the organization filter on HR admin and Sys admin.  only the authorized organization are limit to select on the filter under HR admin page.
2.  New chart "Active Goal Tags" added for both HRadmin and Sysadmin 

Thanks.

**Comment by Travis-A-Clark** [comment]
@jp-Telus This looks really good. Thanks! Three things:

1) I still get a "504 error - gateway timed out" most of the time in the Dev environment. Can we push this to Prod so that I can see how it reacts with the better server and memory space there? The version that is in Prod currently only shows 58 users in the Sys Admin view of Statistics and Reports and it doesn't have the Goal Tags element.

2) The labels for your filters say Organization, Program, Division, Branch, etc. Can we please update these to Organization, Level 1, Level 2, Level 3, Level 4.

3) Can we add the ability to download an Excel or CSV file for the goal tags chart like we do for the others? Each row would have the usual employee ID, name, org, level 1, 2, 3, 4 and then a column for each tag with a count under each for that employee.

**Comment by jp-Telus** [comment]
@Travis-A-Clark 

The following three request item are done 
1. tested on DEV region on Monday (July 11, 2022), no more  "504 error - gateway timed out" for multiple requests, it could be related to memory resource on DEV region. On the other hand, there are more employee showed on Production regions now after ran the command:syncUserProfiles, more then 38,000 employee will showed on the Statistics and Reporting page. It is ready for your testing.

2) The labels for your filters say Organization, Program, Division, Branch, etc. were changed to Organization, Level 1, Level 2, Level 3, Level 4.

3) The "download an Excel or CSV file" for the goal tags chart are completed and ready for your testing.

Thank you.

**Comment by Travis-A-Clark** [comment]
@jp-Telus Can you apply the same fixes to the HR Admin > Statistics and Reporting view as well? Whatever you did to optimize the Sys Admin > Statistics and Reporting view. I am still getting 504 errors in HR Admin view. Thanks!
