### ISSUE TITLE
Employee cannot see conversation with past supervisor

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#881]
Environment: Prod
Employee: Jennifer Simpson
Supervisor: Suzanne Laird

Suzanne and Jennifer had a conversation in November. Suzanne entered comments and signed off. Suzanne then changed jobs and is no longer Jennifer's supervisor.

Suzanne can still see the conversation on her page:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/f3a0a852-9538-41eb-b089-f5da0cd0fa0c)
<br>

Jennifer doesn't see the conversations:

![image.png](https://images.zenhubusercontent.com/5ffe1f472e351dd9b643025b/d1d936a1-2de7-4b65-9d5e-297763470434)
<br>

This is an example that I was hoping would be fixed by the script we ran to assign roles to the conversation participants. As the employee, Jennifer should always have access to this conversation, even after Suzanne is no longer her supervisor.

**Comment by jizhaogit** [comment]
conversation id 1414 does not have any record for the employee signoff id and supervisor sign off id, and since the "reporting to" relationship has been changed, the script can not track back from this single conversation. but based on the db checking there is a conversation id 1413 that is also for those 2 users and has the right relations because the supervisor signed off.  the script can be corrected by using the 1413 data to update 1414 ones.

**Comment by Travis-A-Clark** [comment]
For conversation 1414, how does the app still know to display it for Suzanne Laird and to show Jennifer Simpson as the other participant?

I'm still getting stuck on understanding how it can be saved and display all the correct information for one participant, but we can't access that same information to make it visible for the other participant.

**Comment by jizhaogit** [comment]
The answer is also related to #880:

in the conversation list for team members, the application will first get the current login user's id. Then query all the conversations' owner is the login user or participants that are included in that user's conversations to get the conversation list.  After that, application will filter out all the conversations have participants that is the login user's supervisor or share supervisors.  that will get a list of conversations for this login user's team members.

this process has an issue for handling a conversation that ONLY has owner's id but does not have either team member's sign off id or supervisor's sign off id, and the relationship between team member's and supervisor has been changed. it will default set all the participants in the result as the login user's team members.

**Comment by jizhaogit** [comment]
@Travis-A-Clark for setting up the role with the issue,  we may need to export all the conversations with the participants that ONLY have owners' information and can not find supervisor/employee relationship from the users table, then manually define the role and import the result back to the participant table.
