### ISSUE TITLE
As an HR/Sys Admin, I want to see how many employees have open or completed conversations

### ISSUE THREAD

**Issue by Travis-A-Clark** [bcgov/performance#930]
**HR Admin or System Admin > Statistics and Reporting > Conversations Summary**

Please add two new pie charts to the Conversations Summary page:

"Employee Has Open Conversation"
- Options are Yes or No  
- Excel download includes columns: Employee ID, Employee Name, Employee Email, Open Conversation (Yes/No), Next Conversation Due Date, Org Levels Info, and Reports To.

"Employee Has Completed Conversation"
- Options are Yes or No
- Excel download includes columns: Employee ID, Employee Name, Employee Email, Completed Conversation (Yes/No), Last Sign-Off Date, Org Levels Info, and Reports To.

The order of the pie charts on the page should be: Next Conversation Due, Employee Has Open Conversation, Employees: Open Conversation, Employee Has Completed Conversation, Employees: Completed Conversations

**Comment by jizhaogit** [comment]
@telusdcinco Can you please help do the code review? thanks

**Comment by telusdcinco** [comment]
@jizhaogit All good.  Please proceed.

**Comment by Travis-A-Clark** [comment]
Optimizing performance to avoid timeout errors.

**Comment by steffipravasi** [comment]
1) Logged in as Jessica Wu. She has HR admin access for BC Public Service Agency only. The default chart numbers in Conversation Status are for all the organization. 
Expected result: Only numbers related to the BC PSA must be displayed. 
![Screenshot 2023-04-11 at 12.20.29 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/8904cb0a-ad15-41da-bf5f-723069f6b4cf)

**Comment by Travis-A-Clark** [comment]
@jizhaogit Also just a reminder that the conversation numbers should not include employees that are excused. It looks correct on the other tabs, but not on the most recent conversations tab.

**Comment by jizhaogit** [comment]
@steffipravasi a new version is pushed in the test.  thanks

**Comment by steffipravasi** [comment]
1) Cannot see any data when any organization is selected for both Sys admin and Hr admin.
![Screenshot 2023-04-11 at 8.35.04 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/96fdd335-6e40-4a8b-b7df-61d28a3df920)

**Comment by jizhaogit** [comment]
due to the change of view **user_demo_jr_view**,  the dept-related filter data does not match. need to check with @telusdcinco about the details

**Comment by jizhaogit** [comment]
@steffipravasi after the overnight process running, the dept info is updated, please kindly help to do a re-test. thanks!

**Comment by steffipravasi** [comment]
1) When I click on Download to Excel, it downloads the excel sheet for the 'Yes' part of the Open and Closed Conversation
Expected result: An excel sheet including all the employees of the org but the Excused employees with the following columns must be downloaded:
Open convo: Employee ID, Employee Name, Employee Email, Open Conversation (Yes/No), Next Conversation Due Date, Org Levels Info, and Reports To
Completed convo: Employee ID, Employee Name, Employee Email, Completed Conversation (Yes/No), Last Sign-Off Date, Org Levels Info, and Reports To
![Screenshot 2023-04-12 at 9.41.21 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/67c2aaec-3dc9-4f48-a179-014fbf03be9c)

**Comment by steffipravasi** [comment]
Employee Has Completed Conversation chart title trimming from both the ends:
![Screenshot 2023-05-30 at 4.30.47 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/80b738d5-01e0-44b8-b6db-118d408bc18b)

**Comment by jizhaogit** [comment]
1. The Download to Excel sheet must include both Yes and No results
fixed

2.Issue for HR only: Receiving a 500 Server Error when clicked on 'No' part of both Employee HAs Open and Completed Conversation
fixed

3. Issue for HR only: The columns Email, Next Convo Due, Reporting To are missing information in the Yes part of the charts' downloaded sheet
fixed

4. Issue for Sys admin only: Receiving a 504 Gateway Time Out error when clicking on the No section of Employee has Completed Conversation. No org is selected, so the data set is huge 37769 employees.
fixed

**Comment by jizhaogit** [comment]
1. The Download to Excel sheet must include both Yes and No results
fixed

2.Issue for HR only: Receiving a 500 Server Error when clicked on 'No' part of both Employee HAs Open and Completed Conversation
fixed

3. Issue for HR only: The columns Email, Next Convo Due, Reporting To are missing information in the Yes part of the charts' downloaded sheet
fixed

4. Issue for Sys admin only: Receiving a 504 Gateway Time Out error when clicking on the No section of Employee has Completed Conversation. No org is selected, so the data set is huge 37769 employees.
fixed

**Comment by steffipravasi** [comment]
Seems like our last fixes are not reflected on Test
1) HRadmin - Receiving the 500 error when clicking on the No part for employee has open and closed convo
![Screenshot 2023-06-09 at 6.53.13 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/e9c4b74b-9e34-47c0-a4ab-506cb5411c46)
2) Hr admin: Travis - Org: BC PSA
Total count in the downloaded sheet for Employee's open conversation mismatches the total in the chart 
3) HR admin: Travis - Org: BC PSA
The sheet from No part of employee has completed conversation and the Download to Excel sheet shows the html code when downloaded the file
![Screenshot 2023-06-09 at 7.03.50 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/bb1562b9-161c-4336-8182-6e3112868751)

**Comment by jizhaogit** [comment]
@steffipravasi the updates are deployed in TEST. should be good now.

**Comment by steffipravasi** [comment]
@jizhaogit For HR admin, the main sheets still does not include the Yes part for employees.
![Screenshot 2023-06-13 at 3.35.44 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/31ba1272-75de-4fa1-8092-0f2d6db8ee16)
Open conversation must have 663 entries but can see only 656
Completed conversation must have 663 but can only see 659 
Working fine for Sys admin

**Comment by Travis-A-Clark** [comment]
Two suggestions to fix the title:

1. In the HR Admin view, it looks like the font size for those two charts is larger than the font size for the three charts above. Can we just reduce the font?
2. If option 1 doesn't work, we can change the titles to "User Has Open Conversation" and "User has Completed Conversation".

**Comment by jizhaogit** [comment]
i applied option 2.

**Comment by steffipravasi** [comment]
Title truncating issue has been addressed
![Screenshot 2023-06-16 at 5.37.52 PM.png](https://images.zenhubusercontent.com/62e1b008ce7d6652fe102828/154fc468-6cfa-48dd-a8bb-9c8c4f352d17)

**Comment by steffipravasi** [comment]
As the main purpose of the ticket is addressed, I am moving this ticket for PO review.
